### ISSUE TITLE
Invalid syntax - Ubuntu 11.04

### ISSUE THREAD

**Issue by ghost** [fluxid/mocp-scrobbler#4]
ariel@bangho:~$ mocp-scrobbler.py
  File "/usr/local/bin/mocp-scrobbler.py", line 366
    print(str(e), file=sys.stderr)
                      ^
SyntaxError: invalid syntax

**Comment by fluxid** [comment]
Hi.
I guess the problem is with Python version.
mocp-scrobbler works only with Python 3.
If you have it installed, you may want to run it this way:
`python3 mocp-scrobbler.py`
or edit first line and change
`#!/usr/bin/env python`
into
`#!/usr/bin/env python3`

**Comment by ghost** [comment]
yes, i run incorrectly. thanks!

daemon mode, can be configurated to start at boot time?

**Comment by fluxid** [comment]
You can run it at boot time using crontab with @reboot which starts task when cron is started. It's described in `man 5 crontab` (but run `crontab -e` as your normal user, as scrobbler needs to be run on the same user MOCP runs)
Or, you can use Gnome's session manager and add scrobbler to start at login time, but _I think_ it would stop after logging out, I'm afraid... I'm not sure as I don't use Gnome.
